name: "Release"
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: readVersion
      run: echo "value=$(uv version --short)" >> "$GITHUB_OUTPUT"
    - run: git config --global user.name 'OPSIE.DEV'
    - run: git config --global user.email "opsie-dev@users.noreply.github.com"
    - run: git tag v${{ steps.readVersion.outputs.value }}
    - run: git push origin v${{ steps.readVersion.outputs.value }}
